PickCat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApps.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views, mentions

urlpatterns = [
    path("main", views.main, name="main"),
    path("map", views.map, name="map"),
    path("mypage", views.mypage, name="mypage"),
    path("register", views.register, name="register"),
    path("register_cat", views.register_cat, name="register_cat"),
    path("register_kitchen", views.register_kitchen, name="register_kitchen"),
    path("chatting", views.chatting, name="chatting"),
    path("image_test", views.image_test, name="image_test"),
    path("", views.intro, name="intro"),
    path("info_cat/<int:cat_id>", views.info_cat, name="info_cat"),
    path("info_kitchen/<int:kitchen_id>",
         views.info_kitchen, name="info_kitchen"),
    path("login", views.login, name="login"),
    path("sign_out", views.sign_out, name="sign_out"),
    path("emergency", mentions.newEmergencyMention, name="emergency"),
    path("getCatMentions", mentions.getCatMentions, name="getCatMentions"),
    path("getKitchenMentions", mentions.getCatMentions, name="getKitchenMentions"),
    path("addfavoritecat/<int:thisCat_id>",
         views.addFavoriteCat, name="addFavoriteCat"),
    path("removefavoritecat/<int:thisCat_id>",
         views.removeFavoriteCat, name="removeFavoriteCat"),
    path("addfavorietkitchen/<int:thisKitchen_id>",
         views.addFavoriteKitchen, name="addFavoriteKitchen"),
    path("removefavoritekitchen/<int:thisKitchen_id>",
         views.removeFavoriteKitchen, name="removeFavoriteKitchen"),
    path("mention_kitchen/<int:thisKitchen_id>",
         views.mention_kitchen, name="mention_kitchen"),
    path("mention_cat/<int:thisCat_id>",
         views.mention_cat, name="mention_cat"),
    path("join1", views.join1, name="join1"),
    path("join2", views.join2, name="join2"),
    path("join3", views.join3, name="join3"),
    path("join4", views.join4, name="join4"),

    path("sign_out", views.sign_out, name="sign_out"),
    path("emergency/<int:cat_id>", mentions.newEmergencyMention, name="emergency"),
    path("getCatMentions", mentions.getCatMentions, name="getCatMentions"),
    path("getKitchenMentions", mentions.getCatMentions, name="getKitchenMentions"),
    path("newCatMentions/<int:cat_id>", mentions.newCatMention, name="newCatMentions"),
    path("newKitchenMentions/<int:kitchen_id>", mentions.newKitchenMentions, name="newKitchenMentions"),
    path(
        "addfavoritecat/<int:thisCat_id>", views.addFavoriteCat, name="addFavoriteCat"
    ),
    path(
        "removefavoritecat/<int:thisCat_id>",
        views.removeFavoriteCat,
        name="removeFavoriteCat",
    ),
    path("addfavoritecat/<int:thisCat_id>",
         views.addFavoriteCat, name="addFavoriteCat"),
    path("removefavoritecat/<int:thisCat_id>",
         views.removeFavoriteCat, name="removeFavoriteCat"),
    path("read_qr", views.read_qr, name="read_qr"),
    path("readQr/<int:kitchen_id>", views.readQRdetail, name="readQRdetail"),
    path("newChat", mentions.newChat, name="newChat"),
    path("getChat", mentions.getChat, name="getChat"),
    path("newchat", views.newchat, name="newchat"),
    path("newCatPost/<int:cat_id>",mentions.newCatPost, name="newCatPost"),
]

mainApps/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
import uuid
import os
import base64
from django.contrib.auth.models import User
from django.conf import settings
from django.templatetags.static import static

# Create your models here.

User = settings.AUTH_USER_MODEL

CDN_URL = 'https://akamai-img.scdn.pw'


def get_cdn_url(url):
    if url.startswith('https://') or url.startswith('http://'):
        b64url = base64.b64encode(url.encode("UTF-8")).decode("UTF-8")
        return f"{CDN_URL}/s:1080:1080/{b64url}"
    else:
        return url


def image_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return f"images/{filename}"


class Kitchen(models.Model):
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    name = models.CharField(max_length=100, null=False, blank=False)
    image = models.ImageField(upload_to=image_path, null=True, blank=True)
    checkIn = models.PositiveSmallIntegerField(
        null=True, blank=True, default=0)
    address = models.CharField(max_length=100, null=False, blank=False)
    registeredAt = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def image_url(self):
        if not self.image:
            return static("img/default_kitchen.png")
        else:
            return get_cdn_url(self.image.url)


class Cat(models.Model):

    ISNEUTERED = (
        ('T', '중성화 O'),
        ('F', '중성화 X'),
        ('U', '알수없음')
    )
    GENDER = (
        ('M', "남자"),
        ("F", "여자"),
        ("U", "알수없음")
    )

    name = models.CharField(max_length=100, null=False, blank=False)
    breed = models.CharField(max_length=20, null=False, blank=False)
    isNeutered = models.CharField(
        max_length=1, choices=ISNEUTERED, null=False, blank=False)
    gender = models.CharField(
        max_length=1, choices=GENDER, null=False, blank=False)
    feature = models.TextField(null=True, blank=True)
    favoriteKitchen = models.ManyToManyField(Kitchen)
    registeredAt = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to=image_path, null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def image_url(self):
        if not self.image:
            return static("img/default_cat.png")
        else:
            return get_cdn_url(self.image.url)


class CatPost(models.Model):
    cat = models.ForeignKey(
        Cat, on_delete=models.CASCADE, null=False, blank=False)
    title = models.CharField(max_length=100, null=False, blank=False)
    article = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class CatPhoto(models.Model):
    post = models.ForeignKey(
        CatPost, on_delete=models.CASCADE, null=False, blank=False)
    image = models.ImageField(upload_to=image_path, null=False, blank=False)
    like = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.post.cat.name} {self.post.title} {self.id}"

    @property
    def image_url(self):
        return get_cdn_url(self.image.url)


class Mention(models.Model):
    TYPE = (
        ('C', "CAT"),
        ("K", "KITCHEN"),
        ("E", "EMERGENCY")
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=False, blank=False)
    mention = models.TextField(null=False, blank=False)
    createdAt = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=1, choices=TYPE,
                            null=False, blank=False)


class Chat(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=False, blank=False)
    message = models.TextField(null=False, blank=False)


class CatMention(models.Model):
    target = models.ForeignKey(
        Cat, on_delete=models.CASCADE, null=False, blank=False)
    mention = models.ForeignKey(
        Mention, on_delete=models.CASCADE, null=True, blank=True)


class KitchenMention(models.Model):
    target = models.ForeignKey(
        Kitchen, on_delete=models.CASCADE, null=False, blank=False)
    mention = models.ForeignKey(
        Mention, on_delete=models.CASCADE, null=True, blank=True)


class EmergencyMention(models.Model):
    target = models.ForeignKey(
        Cat, on_delete=models.CASCADE, null=False, blank=False)
    mention = models.ForeignKey(
        Mention, on_delete=models.CASCADE, null=True, blank=True)


class UserManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, nickname, phoneNumber, longitude, latitude, address, password):
        if not email:
            raise ValueError("Email Needed")
        user = self.model(
            email=self.normalize_email(email),
            nickname=nickname,
            phoneNumber=phoneNumber,
            longitude=longitude,
            latitude=latitude,
            address=address
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.model(
            email=self.normalize_email(email),
            nickname="admin",
            phoneNumber=0,
            longitude=0,
            latitude=0,
            address=0,
            password=password
        )
        user.set_password(password)
        user.is_superuser = True
        user.is_admin = True
        user.is_staff = True

        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):

    objects = UserManager()
    #email, nickname, phoneNumber, longitude, latitude, address, password
    email = models.EmailField(max_length=255, unique=True)
    nickname = models.CharField(
        max_length=20, null=True, blank=True, unique=True)
    phoneNumber = models.CharField(
        max_length=11, null=True, blank=True, unique=True)
    image = models.ImageField(upload_to=image_path, null=True, blank=True)
    longitude = models.DecimalField(
        max_digits=9, decimal_places=6, null=True, blank=True)
    latitude = models.DecimalField(
        max_digits=9, decimal_places=6, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    favoriteCat = models.ManyToManyField(Cat, null=True, blank=True)
    favoriteKitchen = models.ManyToManyField(Kitchen, null=True, blank=True)
    checkIn = models.PositiveSmallIntegerField(
        null=True, blank=True, default=0)
    recentCheckin = models.ForeignKey(Kitchen, on_delete=models.CASCADE, null=True, blank=True, related_name="recentCheckin")

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'

    @property
    def image_url(self):
        if not self.image:
            return static("img/default_user.png")
        else:
            return get_cdn_url(self.image.url)


class ImageTest(models.Model):
    image = models.ImageField(upload_to=image_path, null=False, blank=False)

    def __str__(self):
        return self.image.name

    @property
    def image_url(self):
        return get_cdn_url(self.image.url)

mainApps/templates/emergency.html
<form method="POST" action="">
    {% csrf_token %}
    <br><br>

    <div class="input-positioner">
        <div class="input-bar-wrapper">
            <input type="text" id="input-bar" placeholder="mention" name="mention">
        </div>
        <br>
        <div class="input-bar-wrapper">
            <input type="text" id="input-bar" placeholder="id" name="id">
        </div>


        <div class="">
            <input id="btn-signin" type="submit" value="다음">
        </div>

    </div>
</form>

mainApps/templates/image_test.html
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="image">
    <input type="submit">
</form>

mainApps/templates/info_kitchen.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section class="info_kitchen">
    <article>
        <img class="img_kitchen" src="{{kitchenInfo.image_url}}">
        <div class="imgInfobox">
            <span>{{ kitchenInfo.name}}</span>
            <div>
                <img src="{% static 'img/icon-checkin.png'%}">
                <span>오늘 체크인 </span>
                <span>{{ kitchenInfo.checkIn }}명</span>
            </div>
        </div>
    </article>
    <article>
        <h2 style="font-size:13px;">급식소에 자주 오는 친구들</h2>
        <div class="hr"></div>
        <div class="content">

            {% for cat in kitchenInfo.cat_set.all %}
                    <a class="imgbox" href="{% url 'info_cat' cat.id %}">
                <img src="{{cat.image_url}}">
                <span>{{ cat.name }}</span>
            </a>
            {% endfor %}
        </div>
    </article>
    <div class="buttonbox2">
        <a class="button" href="{% url "read_qr" %}">
            <img src="{% static 'img/icon-barcode.png'%}">
            <span>QR출석하기</span>
        </a>

            {% if isFavorite %}
                <a class="button" href="{% url 'removeFavoriteKitchen' kitchenInfo.id %}">
                <img src="{% static 'img/icon-pick.png'%}">
                <span>UnPick</span>
            {% else %}
                <a class="button" href="{% url 'addFavoriteKitchen' kitchenInfo.id %}">
                <img src="{% static 'img/icon-heart.png'%}">
                <span>Pick</span>
            {% endif %}
        </a>
        <a class="button" href="{% url "mention_kitchen" kitchenInfo.id %}">
            <img src="{% static 'img/icon-message.png'%}">
            <span>멘션쓰기</span>
        </a>
    </div>
    <article>
        <h2>실시간 멘션</h2>
        <div class="hr"></div>
        <div class="content" style="overflow-x: scroll;">
            <div class="mention_container2" style="display:flex">
                {% for mention in kitchenMentions %}
                <div class="mention_box2"> 
                    <img src="{{ mention.mention.user.image_url }}">
                    <div class="mention_text"><span style="color:#ceffbf;">@ {{ mention.mention.user.nickname }}</span>&nbsp;&nbsp;{{ mention.mention.mention }}</div>
                </div>
                {% endfor %}
            </div>
        </div>
    </article>

</section>
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    let mention = document.querySelectorAll('.mention_box2').length*390+'px';
    $(".mention_container2").css("width",mention);
</script>
{% endblock %}

mainApps/templates/join.html
{% extends 'signbase.html' %} 
{% block content %} 
{% load static %}


    <header>
        <div class="topbar-sign">
            <span>
                회원가입
            </span>
        </div>
    </header>

    <div id="main-title" style="width:90%; margin:0 auto;">
        <span style="color:black; ">가입 정보 입력</span><br>
        <span style="color:black; ">픽켓과 함께 집사 될 준비되셨나요?</span>
    </div>

    <form method="POST" action="{% url 'join'%}">
        {% csrf_token %}
        <br><br>
        
        <div class="input-positioner">
            <div class="input-bar-wrapper">
                <input type="text" id="input-bar" placeholder="이메일을 입력해주세요" name="username">
            </div>
            <br>
            <div class="input-bar-wrapper">
                <input type="password" id="input-bar" placeholder="비밀번호를 입력해주세요" name="password">
            </div>
            <br>
            <div class="input-bar-wrapper">
                <input type="password" id="input-bar" placeholder="비밀번호 확인" name="password">
            </div>
            <input id="btn-signin" type="submit" value="다음">
        </div>
      </div>
    </form>
    
    {% endblock %}

mainApps/templates/join2.html
{% extends 'signbase.html' %} {% block content %}
<header>
  <div class="topbar-sign">
    <span> 프로필 </span>
    <div class="topbar-line"></div>
  </div>
</header>

<div id="main-title">
  <span id="title-1" style="color: black">프로필 설정 </span><br />
  <span id="title-2" style="color: black">닉네임과 프로필 사진을 등록해주세요 </span>
</div>

<form method="POST" action="{% url 'join3'%}" enctype="multipart/form-data">
  {% csrf_token %}
  <br /><br />

  <div class="input-positioner">
    <div class="input-box-wrapper">
      <img src="../static/img/join2-user.png" id="join2-user-image" style="width: 165px; height: 161px;">
      <input type="file" id="input-bar2" name="image" size="10" />

      <br />
      <div class="input-bar-wrapper">
        <input name="nickname" id="input-bar-join2" type="text" placeholder="닉네임을 입력해주세요" />
      </div>
      <br />

    </div>

    <div class="">
      <button id="btn-signin" type="submit">
        다음
      </button>
    </div>
  </div>
</form>

{% endblock %}

mainApps/templates/join3.html
{% extends 'signbase.html' %} {% block content %}
<header>
  <div class="topbar-sign">
    <span> 동네 인증 </span>
    <div class="topbar-line"></div>
  </div>
</header>
<div id="map" style="width: 100%; height: 350px"></div>
<div id="clickLatlng"></div>

<form method="POST" action="{% url 'join4'%}" enctype="application/x-www-form-urlencoded"
  onkeydown="return event.key != 'Enter';" onsubmit="return verifyForm(event)">
  {% csrf_token %}
  <br /><br />

  <input type="hidden" name="latitude" id="lat" />

  <br />
  <input type="hidden" name="longitude" id="lng" />
  <input type="hidden" name="address" id="addr" />
  <p id="address">지도를 클릭해 위치를 지정 해주세요</p>
  <button id="btn-signin" type="submit">
    다음
  </button>
</form>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=f46e5561c28ddbcaa52d31253347ebcb"></script>
<script>
  var mapContainer = document.getElementById("map"), // 지도를 표시할 div
    mapOption = {
      center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
      level: 3, // 지도의 확대 레벨
    };

  var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

  // 지도를 클릭한 위치에 표출할 마커입니다
  var marker = new kakao.maps.Marker({
    // 지도 중심좌표에 마커를 생성합니다
    position: map.getCenter(),
  });
  // 지도에 마커를 표시합니다
  marker.setMap(map);

  // 지도에 클릭 이벤트를 등록합니다
  // 지도를 클릭하면 마지막 파라미터로 넘어온 함수를 호출합니다
  kakao.maps.event.addListener(map, "click", function (mouseEvent) {
    // 클릭한 위도, 경도 정보를 가져옵니다
    var latlng = mouseEvent.latLng;

    // 마커 위치를 클릭한 위치로 옮깁니다
    marker.setPosition(latlng);

    document.getElementById("lat").value = latlng.getLat();
    document.getElementById("lng").value = latlng.getLng();
    getAddressFromLocations(latlng.getLng(), latlng.getLat())

  });
  function getAddressFromLocations(x, y) {
    document.getElementById('address').innerText = "주소 정보를 받아오는 중입니다. 잠시만 기다려주세요."
    url = `https://pickcat-kapi-proxy.jaewon.dev/v2/local/geo/coord2regioncode.json?x=${x}&y=${y}`
    Http = new XMLHttpRequest();
    Http.open("GET", url, true);
    Http.responseType = 'json';
    Http.send();
    Http.onreadystatechange = (e) => {
      if (Http.readyState == 4 && Http.status == 200) {
        data = Http.response;
        document.getElementById('address').innerText = data.documents[0].address_name
        document.getElementById('addr').value = data.documents[0].address_name
        window.address_found = 1;
      }
    }
  }
  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function (position) {
        x = position.coords.longitude
        y = position.coords.latitude
        map.setCenter(new kakao.maps.LatLng(y, x))
        document.getElementById('longitude').value = x;
        document.getElementById('latitude').value = y;
        getRegionFromLocation(x, y)
      }, function (error) {
        alert(`위치 정보를 받아올 수 없습니다.\n${error}`)
      }, {
        enableHighAccuracy: true,
        maximumAge: 0,
        timeout: Infinity
      });
    }
  }
  getLocation()
  function verifyForm(e) {
    if (!window.address_found) {
      alert('위치 정보를 불러와주세요');
      return false
    }
    return true;
  }

</script>
{% endblock %}

mainApps/templates/map.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section class="map" style="position:relative;">
    <div id="map" style="width:100%;height:710px;"></div>

    <div class="map_box">
        <img src="{% static 'img/kitchen.png'%}">
        <div class="map_comment">
            <span>인경호 급식소</span><br>
            <span style="font-size: 12px; color:gray;">인천 미추홀구 인하로 100</span>
        </div>
        <span class="icon_out">X</span>
    </div>

</section>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=e3f4fcd64134ce1b708dc9dae8e3bc0e">
</script>
<script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = {
            center: new kakao.maps.LatLng(37.450463848354794, 126.6562767047894), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨

        };

    // 지도를 표시할 div와  지도 옵션으로  지도를 생성합니다
    var map = new kakao.maps.Map(mapContainer, mapOption);
    var marker = new kakao.maps.Marker({
        // 지도 중심좌표에 마커를 생성합니다
        position: new kakao.maps.LatLng(37.450463848354794, 126.6562767047894),
    });
    // 지도에 마커를 표시합니다
    marker.setMap(map);
</script>

{% endblock %}

mainApps/templates/mention_cat.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section class="mention">
    <form method="POST" action="{% url "newCatMentions" cat.id %}">
        <div class="mention_items" style="width:100%;">
            <img src="{% static 'img/icon-cat.png'%}" style="width:20px">
            <span>{{ cat.name }}</span>
        </div>
        <div class="mention_items">
            <img src="{{ cat.image_url }}">
            <span>{{ request.user.nickname }} 집사님의 <span style="color:#8B8CEC">픽캣멘션</span></span>
        </div>
        <div class="mention_items">오늘 {{ cat.name }}는(은) 어때 보이나요?</div>
        <div class="mention_items">
            <div class="items_row">
                <div class="mention_button">
                    <img src="{%static 'img/icon-rice.png'%}">&nbsp;&nbsp;<span class="mention_span">즐거워 보여요!</span>
                </div>
                <div class="mention_button">
                    <img src="{%static 'img/icon-clap.png'%}">&nbsp;&nbsp;<span class="mention_span">우울해 보여요ㅠㅠ</span>
                </div>
            </div>
            <div class="items_row">
                <div class="mention_button">
                    <img src="{%static 'img/icon-candy.png'%}">&nbsp;&nbsp;<span class="mention_span">오늘도 잘 자는중~</span>
                </div>
                <div class="mention_button">
                    <img src="{%static 'img/icon-man.png'%}">&nbsp;&nbsp;<span class="mention_span">기타사항 멘션 작성하기</span>
                </div>
            </div>
            <input class="mention_value" type="text" name="mention" placeholder="기타사항을 작성해주세요" required style="width:90%; display:block; margin:0 auto; border-radius: 25px; padding:5px; visibility: hidden;">
        </div>
        
        <input type="submit" value="완료"/>
        {% csrf_token %}
    </form>
</section>

{% endblock %}

mainApps/templates/mypage.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<section class="mypage">
    <h3>{{ request.user.nickname}}님의 마이 픽캣스토리</h3>
    <article
        style="padding-bottom:0; margin-bottom: 30px; background-color: #fefeff;filter:drop-shadow(0px 5px 3px #f7f7f7);">
        <div class="mypage_box1">
            <img src="{{request.user.image_url}}">
            <div class="mention_items" style="width:100%;">
                <span><img src="{% static 'img/icon-marker.png'%}">&nbsp;{{ request.user.address}}에서&nbsp;<span
                        style="color:#8B8CEC;">픽캣 중!</span></span>
            </div>
            <div id="btn-signin-mypage" onclick="location.href='join3'">
                동네 위치 변경
            </div>
        </div>
        <div class="mypage_box2">

            {% if attendaceBadge == True %}

            <div class="mypage_box3">
                <div style="text-align:center; ">
                    <img src="{% static "img/icon-badge.png" %}">
                    <br>
                    <span style="color:#707070;  font-weight: bold; font-size: 13px;">집사님은 급식소 프로 참석러</span>
                    <br>
                    <span style="color:#ECAB31; font-weight: bold; font-size: 13px;">방문왕 배찌 획득완료!</span>
                </div>
            </div>

            {% endif %}



            <div class="mypage_box4">
                <div>
                    <span style="color:#8B8CEC; font-size: 14px;">체크인 급식소</span>
                    {% if user.recentCheckin %}
                    <a href="{% url "info_kitchen" user.recentCheckin.id %}"
                        style="text-decoration: underline; color:rgb(87, 87, 87); font-weight: 600;">{{ user.recentCheckin }}</a>
                    {% endif %}
                </div>
                <div style="color:rgb(87, 87, 87); font-size: 14px;">
                    급식소 체크인&nbsp;<span style="color:#8B8CEC;">총 {{ user.checkIn }}회</span>
                </div>
            </div>
        </div>
    </article>

    <article>
        <h2>My pick</h2>
        <div class="hr"></div>
        <div class="content">
            <div class="imgbox-container">
                {% for cat in user.favoriteCat.all %}
                <div class="imgbox">
                    <a href="{% url 'info_cat' cat.id %}"><img src="{{ cat.image_url }}"></a>
                    <span>{{ cat.name }}</span>
                </div>
                {% endfor %}
            </div>
        </div>
    </article>
    <a class="logout_box" href="{%url 'sign_out'%}">로그아웃</a>
</section>



{% endblock %}

mainApps/templates/register_cat.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section class="register">

  <form action="{% url 'register_cat' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <div class="register_header">
      <a href="{% url 'register_cat'%}" class="button" style="color:#8B8CEC;"><span>고양이 등록하기</span></a>
      <a href="{% url 'register_kitchen'%}" class="button"><span>급식소 등록하기</span></a>
    </div>
    <div class="register_article"> 
      <span>고양이 사진 등록</span>
      <input class="input_box" type="file" name="uploadedImage" style="line-height: 35px;">
    </div>

    <div class="register_article">
      <span>고양이 기본 정보</span>
      <input class="input_box" type="text" name="name" placeholder="  고양이의 이름을 입력해주세요" required>
      <select class="input_box" name="kitchenid" style="color:gray;" required>
        <option value="" disabled selected>&nbsp;어떤 급식소에서 고양이를 만났나요?</option>
        {% for k in kitchen %}
        <option value="{{ k.id }}">{{ k.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="register_article">
      <span>특징을 입력해주세요</span>
      <input class="input_box" type="text" name="feature" placeholder="  예) 사람을 좋아해요, 줄무늬가 있어요">
    </div>
    <div class="register_article">
      <span>성별을 선택해 주세요</span><br>
      <input type="radio" name="gender" value="M" style="margin-top: 10px;">&nbsp;수컷<br>
      <input type="radio" name="gender" value="F">&nbsp;암컷<br>
      <input type="radio" name="gender" value="U" checked>&nbsp;모름<br>
    </div>
    <div class="register_article">
      <span>중성화 여부를 선택해 주세요</span><br>
      <input type="radio" name="isNeutered" value="T" style="margin-top: 10px;">&nbsp;O<br>
      <input type="radio" name="isNeutered" value="F">&nbsp;X<br>
      <input type="radio" name="isNeutered" value="U" checked>&nbsp;모름<br>
    </div>
    <div class="register_article">
      <span>품종을 입력해주세요</span>
      <input class="input_box" type="text" name="breed" placeholder="  예) 코숏">
    </div>
    <br>
    <input type="submit" value="완료"><br><br>
</section>
</form>
</section>
{% endblock %}